version: '3'
services:
   postgres-web:
     image: postgres:9.6
     container_name: postgres-web
     ports:
       - 5432:5432
     environment:
       POSTGRES_DB: aplicacao
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: senha
     restart: always
     stdin_open: true
     tty: true

   web:
     image: fabricainfo/assinatura_digital:1.0
     container_name: web
     volumes:
       - ./:/var/www/html/
     ports:
       - 8000:80
     links:
       - postgres-web:postgres-web
     working_dir: "/var/www/html"
     restart: always
     stdin_open: true
     tty: true